---
name: Go
on: [ push, pull_request ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.16.x
          - tip
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/go/src/gopkg.in/yaml.v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go get -t ./...
        working-directory: ${{ github.workspace }}/go/src/github.com/alexeyco/pbn
      - run: go test .
        working-directory: ${{ github.workspace }}/go/src/github.com/alexeyco/pbn
